apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: your-docker-registry/your-spring-boot-app-image:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: products-application-properties
---
apiVersion: v1
kind: Service
metadata:
  name: products-svc
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  